#!/usr/bin/env python3
"""Extract the BIOS-icon palette + 4bpp bitmap from an ICONDATA_VMS and
emit src/library/gen_library_icon.h. The library save (VMUICONS.VMS)
uses these bytes verbatim for its VMS header's icon slot, so dropping a
new ICONDATA in assets/library_icon/ and re-running this updates the
icon shown for the library file in the Dreamcast BIOS file manager.

ICONDATA_VMS layout (Sega spec, mirrors dc/src/vms/vms.c decode):
    0x00..0x0F  description text (16 bytes)
    0x14        0xA0 if a color icon is present
    0x20..0x9F  mono icon (32x32 1bpp = 128 bytes)
    0xA0..0xBF  16-entry ARGB4444 palette (32 bytes)
    0xC0..0x2BF color icon, 4bpp packed (512 bytes)
    0x2C0..     optional real-mode signature + padding

Usage (manual or via the Makefile rule):
    python3 buildtools/make_library_icon.py \
        assets/library_icon/ICONDATA.VMS \
        src/library/gen_library_icon.h
"""
import sys
from pathlib import Path

PALETTE_OFF, PALETTE_LEN = 0xA0, 32
BITMAP_OFF,  BITMAP_LEN  = 0xC0, 512


def emit_array(name, data, per_row=12):
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_row):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + per_row])
        out.append(f"    {chunk},")
    out.append("};")
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        print("usage: make_library_icon.py <ICONDATA.VMS> <out.h>", file=sys.stderr)
        sys.exit(2)

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])

    data = src.read_bytes()
    if len(data) < BITMAP_OFF + BITMAP_LEN:
        sys.exit(f"{src}: too small ({len(data)} bytes); not a valid ICONDATA_VMS")
    if data[0x14] != 0xA0:
        print(f"warning: {src} byte 0x14 = 0x{data[0x14]:02x} (expected 0xA0 "
              "for color icon present); proceeding anyway", file=sys.stderr)

    palette = data[PALETTE_OFF:PALETTE_OFF + PALETTE_LEN]
    bitmap  = data[BITMAP_OFF:BITMAP_OFF + BITMAP_LEN]
    full    = data            # whole 1024-byte ICONDATA_VMS blob

    description = data[0:16].rstrip(b"\x00 ").decode("ascii", errors="replace")

    header = f"""\
/* gen_library_icon.h -- GENERATED by buildtools/make_library_icon.py.
 *
 * Source: {src.name} (description: {description!r})
 *
 * Baked Joypad-logo icon assets. Two consumers:
 *   - library.c memcpys the palette + 4bpp bitmap directly into the
 *     library save's VMS header (its BIOS icon).
 *   - apply.c writes the FULL ICONDATA_VMS blob when a VMU has none,
 *     so VMU-level toggles (like Real Mode / 3D BIOS) have a file to
 *     attach to. Refresh by dropping a new ICONDATA into
 *     assets/library_icon/ and rerunning the Makefile. Don't hand-edit. */
#ifndef GEN_LIBRARY_ICON_H
#define GEN_LIBRARY_ICON_H

#include <stdint.h>

/* ARGB4444 palette, 16 entries; packed as (g<<4|b, a<<4|r) per entry. */
{emit_array('joypad_logo_palette', palette)}

/* 32x32 4bpp packed color bitmap (high nibble = even column). */
{emit_array('joypad_logo_bitmap', bitmap)}

/* Full 1024-byte ICONDATA_VMS file (description + mono icon + palette +
 * color bitmap), ready to vmufs_write straight to a VMU's root. */
{emit_array('joypad_logo_icondata_full', full)}

#endif /* GEN_LIBRARY_ICON_H */
"""
    dst.write_text(header)
    print(f"wrote {dst} ({len(palette)}+{len(bitmap)} bytes from {src})")


if __name__ == "__main__":
    main()
