#!/usr/bin/env python3
"""Extract the 128-byte mono icon from an ICONDATA_VMS and emit
src/library/gen_fallback_vmu_icon.h. Used by browser.c as the fallback
rendered for VMUs without an ICONDATA_VMS when the BIOS preset shape
isn't available (e.g. running under Flycast, whose stub font omits the
VMU icon section).

ICONDATA_VMS mono icon is 32x32 1bpp at offset 0x20, MSB-first per
byte, stored UPRIGHT in this project's file layout (see jt_vms_encode /
draw_thumb). We pre-flip it H+V here to match bfont's LCD-native
convention so browser.c's draw_preset_icon can feed it through the
same unflip path it uses for BIOS preset icons.

Usage (via the Makefile rule):
    python3 buildtools/make_fallback_vmu_icon.py \\
        assets/fallback_vmu_icon/ICONDATA.VMS \\
        src/library/gen_fallback_vmu_icon.h
"""
import sys
from pathlib import Path

MONO_OFF, MONO_LEN = 0x20, 128


def emit_array(name, data, per_row=12):
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_row):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + per_row])
        out.append(f"    {chunk},")
    out.append("};")
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        print("usage: make_fallback_vmu_icon.py <ICONDATA.VMS> <out.h>",
              file=sys.stderr)
        sys.exit(2)

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])

    data = src.read_bytes()
    if len(data) < MONO_OFF + MONO_LEN:
        sys.exit(f"{src}: too small ({len(data)} bytes); not a valid ICONDATA_VMS")

    mono = data[MONO_OFF:MONO_OFF + MONO_LEN]
    # Stored upright (row-major, MSB-first) and rendered directly by
    # browser.c's draw_preset_icon -- no flip needed.

    description = data[0:16].rstrip(b"\x00 ").decode("ascii", errors="replace")

    header = f"""\
/* gen_fallback_vmu_icon.h -- GENERATED by make_fallback_vmu_icon.py.
 *
 * Source: {src.name} (description: {description!r})
 *
 * Fallback rendered for VMUs without an ICONDATA_VMS when the BIOS
 * preset icon isn't available (e.g. Flycast's stub BIOS font). On real
 * hardware bfont_find_icon returns the actual ROM-baked shape; this
 * bitmap is the emulator fallback. Native VMU LCD format -- MSB-first
 * per byte, H+V flipped vs. upright. */
#ifndef GEN_FALLBACK_VMU_ICON_H
#define GEN_FALLBACK_VMU_ICON_H

#include <stdint.h>

/* 32x32 1bpp mono icon, 128 bytes. */
{emit_array('fallback_vmu_icon_mono', mono)}

#endif /* GEN_FALLBACK_VMU_ICON_H */
"""
    dst.write_text(header)
    print(f"wrote {dst} ({len(mono)} bytes from {src})")


if __name__ == "__main__":
    main()
