#!/usr/bin/env python3
"""Extract the 124 VMU preset icons from a BIOSDUMP.VMS-format file and
emit src/library/gen_bios_icons.h.

The dump is a 640-byte VMS header followed by 124 x 128-byte 1bpp icons
(upright, row-major, MSB-first per byte) in shape-index order
(index 0 == BFONT_ICON_VMUICON). browser.c uses this table as the
emulator fallback for VMUs without ICONDATA; real hardware still pulls
icons from the console's own BIOS via bfont_find_icon.

Usage (via the Makefile rule):
    python3 buildtools/make_bios_icons.py \\
        assets/bios_icons/BIOSDUMP.VMS \\
        src/library/gen_bios_icons.h
"""
import sys
from pathlib import Path

HDR = 640
N = 124
SZ = 128


def emit_array(name, data, per_row=16):
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_row):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + per_row]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        print("usage: make_bios_icons.py <BIOSDUMP.VMS> <out.h>", file=sys.stderr)
        sys.exit(2)
    src = Path(sys.argv[1]); dst = Path(sys.argv[2])
    data = src.read_bytes()
    payload = data[HDR:HDR + N * SZ]
    if len(payload) < N * SZ:
        sys.exit(f"{src}: too small ({len(data)} bytes); expected a "
                 f"BIOSDUMP.VMS with {N} {SZ}-byte icons")
    hdr = f"""\
/* gen_bios_icons.h -- GENERATED by buildtools/make_bios_icons.py.
 *
 * Source: {src.name}
 *
 * 124 VMU preset icons (shape 0 == BFONT_ICON_VMUICON .. 123 ==
 * BFONT_ICON_EMBROIDERY), 32x32 1bpp, upright row-major MSB-first.
 * Emulator fallback in browser.c; real hardware uses bfont_find_icon.
 * Don't hand-edit -- rerun the generator. */
#ifndef GEN_BIOS_ICONS_H
#define GEN_BIOS_ICONS_H

#include <stdint.h>

{emit_array('bios_icons_mono', bytes(payload))}

#endif /* GEN_BIOS_ICONS_H */
"""
    dst.write_text(hdr)
    print(f"wrote {dst} ({N} icons from {src})")


if __name__ == "__main__":
    main()
