#!/usr/bin/env python3
"""Generate src/ui/gen_logo.h: a 1-bit silhouette mask of the joypad logo
for the Dreamcast tester's idle screensaver.

Mirrors the gcn/buildtools/make_logo.py pattern: the source PNG gets
cropped to its silhouette bbox, scaled into a square mask, and packed
into a byte array (MSB-first). The screensaver renders each set bit
as the current cycle color and leaves clear bits transparent.

Source:
    dc/assets/screensaver-logo.png (preferred)
    dc/assets/logo.png             (fallback; copied from the shared
                                    assets/ logo at scaffold time)
"""
import sys
from pathlib import Path
from PIL import Image

LOGO_W = 128
LOGO_H = 128

HERE = Path(__file__).parent
PROJECT = HERE.parent
OUT = PROJECT / 'src' / 'ui' / 'gen_logo.h'

CANDIDATES = [
    PROJECT / 'assets' / 'screensaver-logo.png',
    PROJECT / 'assets' / 'logo.png',
]


def find_source() -> Path:
    for p in CANDIDATES:
        if p.exists():
            return p
    sys.exit('No source PNG found; tried: ' +
             ', '.join(str(p) for p in CANDIDATES))


def pack_mask(flat: Image.Image, max_w: int, max_h: int):
    """Crop `flat` (grayscale, dark = silhouette) to its silhouette bbox,
    resize to fit inside max_w × max_h while preserving aspect ratio,
    pack into a 1-bit mask (MSB-first per byte). Width is rounded down
    to a multiple of 8 so each row fits cleanly into byte boundaries."""
    bw = flat.point(lambda v: 255 if v < 128 else 0, 'L')
    bbox = bw.getbbox()
    src = flat.crop(bbox) if bbox else flat
    sw, sh = src.size
    scale = min(max_w / sw, max_h / sh)
    w = max(8, (int(sw * scale) // 8) * 8)
    h = max(1, int(sh * scale))
    scaled = src.resize((w, h), Image.LANCZOS)
    bytes_per_row = w // 8
    packed = bytearray(bytes_per_row * h)
    lit = 0
    for y in range(h):
        for x in range(w):
            if scaled.getpixel((x, y)) < 128:
                packed[y * bytes_per_row + x // 8] |= 0x80 >> (x % 8)
                lit += 1
    return packed, bytes_per_row, lit, w, h


def emit_mask(f, name: str, w: int, h: int, packed: bytes,
              bytes_per_row: int, lit: int) -> None:
    upper = name.upper()
    f.write(f'// {w}x{h} silhouette mask, {lit} lit px.\n')
    f.write(f'#define {upper}_W {w}\n')
    f.write(f'#define {upper}_H {h}\n')
    f.write(f'#define {upper}_BYTES_PER_ROW {bytes_per_row}\n')
    f.write(f'static const unsigned char {name}_mask[{len(packed)}] = {{\n')
    line = []
    for i, b in enumerate(packed):
        line.append(f'0x{b:02x}')
        if (i + 1) % 16 == 0:
            f.write('  ' + ', '.join(line) + ',\n')
            line = []
    if line:
        f.write('  ' + ', '.join(line) + ',\n')
    f.write('};\n\n')


def main() -> None:
    src = find_source()
    img = Image.open(src).convert('RGBA')
    bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
    flat = Image.alpha_composite(bg, img).convert('L')

    packed, bpr, lit, w, h = pack_mask(flat, LOGO_W, LOGO_H)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open('w') as f:
        f.write('// Auto-generated by buildtools/make_logo.py - DO NOT EDIT.\n')
        f.write(f'// Source: {src.relative_to(PROJECT)}\n\n')
        f.write('#ifndef GEN_LOGO_H\n#define GEN_LOGO_H\n\n')
        emit_mask(f, 'logo', w, h, packed, bpr, lit)
        f.write('#endif  // GEN_LOGO_H\n')
    print(f'wrote {OUT.relative_to(PROJECT)} ({w}x{h}, {lit} lit px)')


if __name__ == '__main__':
    main()
