#!/usr/bin/env python3
"""Generate ppc/gen_logo.h: a 1-bit alpha mask of the joypad logo for the
screensaver.

Source: branding/screensaver-logo.png (preferred) or
        branding/logo.png (fallback) or
        ../../branding/logo_solid.png (joypad shared)

The mask gets rendered each frame in the cycle color so the screensaver
can color-shift on every wall bounce while the silhouette stays crisp.
"""

import sys
from pathlib import Path

from PIL import Image

LOGO_W = 160
LOGO_H = 160

HERE = Path(__file__).parent
PROJECT = HERE.parent
OUT = PROJECT / 'ppc' / 'gen_logo.h'

CANDIDATES = [
    PROJECT / 'branding' / 'screensaver-logo.png',
    PROJECT / 'branding' / 'logo.png',
]


def find_source() -> Path:
    for p in CANDIDATES:
        if p.exists():
            return p
    sys.exit('No source PNG found; tried: ' + ', '.join(str(p) for p in CANDIDATES))


def main() -> None:
    src = find_source()
    img = Image.open(src).convert('RGBA')

    # Composite alpha onto white. Source logos are typically dark icon on
    # transparent → after composite we get dark icon on white. Threshold the
    # grayscale: dark = "lit" (the silhouette), light = "unlit" (background).
    bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
    flat = Image.alpha_composite(bg, img).convert('L')
    scaled = flat.resize((LOGO_W, LOGO_H), Image.LANCZOS)

    # Pack into 1-bit mask, MSB-first per byte.
    bytes_per_row = LOGO_W // 8
    packed = bytearray(bytes_per_row * LOGO_H)
    lit_count = 0
    for y in range(LOGO_H):
        for x in range(LOGO_W):
            lit = scaled.getpixel((x, y)) < 128
            if lit:
                packed[y * bytes_per_row + x // 8] |= 0x80 >> (x % 8)
                lit_count += 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open('w') as f:
        f.write(f'// Auto-generated by buildtools/make_logo.py — DO NOT EDIT.\n')
        f.write(f'// Source: {src}\n')
        f.write(f'// {LOGO_W}x{LOGO_H} 1-bit alpha mask, MSB-first.\n')
        f.write(f'// {lit_count} lit pixels of {LOGO_W * LOGO_H}.\n\n')
        f.write('#ifndef GEN_LOGO_H\n#define GEN_LOGO_H\n\n')
        f.write(f'#define LOGO_W {LOGO_W}\n')
        f.write(f'#define LOGO_H {LOGO_H}\n')
        f.write(f'#define LOGO_BYTES_PER_ROW {bytes_per_row}\n\n')
        f.write(f'static const unsigned char logo_mask[{len(packed)}] = {{\n')
        line = []
        for i, b in enumerate(packed):
            line.append(f'0x{b:02x}')
            if (i + 1) % 16 == 0:
                f.write('  ' + ', '.join(line) + ',\n')
                line = []
        if line:
            f.write('  ' + ', '.join(line) + ',\n')
        f.write('};\n\n')
        f.write('#endif  // GEN_LOGO_H\n')
    print(f'wrote {OUT} ({len(packed)} bytes mask, {lit_count} lit px)')


if __name__ == '__main__':
    main()
